### PR TITLE
Add PHP, improve run_all_tests script

### PR DESCRIPTION
**Pull request by brewneaux**

### CODE REVIEW

**Comment by stuartaroth** [comment]
@brewneaux Awesome I love how you improved the run_all_tests.
I want to merge this in as soon as possible but there are just a two things to consider before it gets in.

First: PHP doesn't appear to be part of the run_all_tests script, and it should be now. Also it should include the two other languages that were recently added: Dart and Kotlin. You'll want to merge master into the branch.

Second: variables.php appears to be empty. Is this what you wanted?

Overall it all looks great and the new and improved run_all_tests script is going to be awesome. Thanks for your contribution!

**Comment by stuartaroth** [comment]
@brewneaux if you're busy though, I can take care of the additions myself. Just let me know! I know you said you were going to be busy.

**Comment by brewneaux** [comment]
@stuartaroth I finally got around to this again - do you want me update this after the merge, or did you fix it?

**Comment by stuartaroth** [comment]
@brewneaux I think I already made all the updates. Thanks though!

**Pull request merged**
