### PR TITLE
Final ^_^

### PR DESCRIPTION
**Pull request by BasilArackal**

### CODE REVIEW

**Comment by stuartaroth** [comment]
@BasilArackal Hey awesome work! I'm excited to get this merged in as soon as possible. I just have two concerns:
1. The arrays_lists/example.cpp file is empty. I'm not sure familiar with C++ but could a vector be used here? What do you normally use to get something like an ArrayList?
2. The arrays_lists_iteration/example.cpp does not compile with just plain g++. Every other file you've written compiles fine. Are there certain options or dependencies needed for this file to compile?

**Comment by BasilArackal** [comment]
Oops! I'll fix that up right away! sorry about that I was swapping b/w two editors and might have messed it up right before commit. @stuartaroth great work btw with the site really useful I must say

**Comment by BasilArackal** [comment]
And @stuartaroth  arrays_lists_iteration/example.cpp compiled fine on g++ (Ubuntu 5.3.1-14ubuntu2.1) 5.3.1 20160413
 for me it's Ubuntu 16.04 btw could you perhaps check again on that? Thanks ^_^

**Comment by BasilArackal** [comment]
Added Content to the empty Array_lists example for C++

**Comment by stuartaroth** [comment]
@BasilArackal 
Awesome with the array_lists. And my bad it was actually the hash_maps_iteration/example.cpp that fails to compile with g++. I tested on OSX and on Ubuntu 15. Here's the output from OSX:

`$ g++ hash_maps_iteration/example.cpp
hash_maps_iteration/example.cpp:15:34: error: no viable conversion from '__map_iterator<__tree_iterator<__value_type<std::__1::basic_string<char>, [...]>,
      std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char>, int>, void *> *, [...]>>' to '__map_iterator<__tree_iterator<__value_type<char, [...]>,
      std::__1::__tree_node<std::__1::__value_type<char, int>, void *> *, [...]>>'
    for (map<char,int>::iterator i=hashMap.begin(); i!=hashMap.end(); ++i)
                                 ^ ~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:694:29: note: candidate constructor (the implicit copy constructor)
      not viable: no known conversion from 'iterator' (aka '__map_iterator<__tree_iterator<std::__1::__value_type<std::__1::basic_string<char>, int>,
      std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char>, int>, void *> *, long> >') to 'const
      std::__1::__map_iterator<std::__1::__tree_iterator<std::__1::__value_type<char, int>, std::__1::__tree_node<std::__1::__value_type<char, int>, void *> *, long> > &' for 1st
      argument
class _LIBCPP_TYPE_VIS_ONLY __map_iterator
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:719:5: note: candidate constructor not viable: no known conversion
      from 'iterator' (aka '__map_iterator<__tree_iterator<std::__1::__value_type<std::__1::basic_string<char>, int>,
      std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char>, int>, void *> *, long> >') to 'std::__1::__tree_iterator<std::__1::__value_type<char, int>,
      std::__1::__tree_node<std::__1::__value_type<char, int>, void *> *, long>' for 1st argument
    __map_iterator(_TreeIterator __i) _NOEXCEPT : __i_(__i) {}
    ^
1 error generated.`

**Comment by BasilArackal** [comment]
It needs the -std=c++11 flag on g++ compilers sorry about that!

**Comment by stuartaroth** [comment]
@BasilArackal Awesome great work. I'll work on getting this into the site tonight. Thanks for all your contributions!

**Comment by BasilArackal** [comment]
Happy to help! Great work yourself @stuartaroth  I was thinking on making an android app from the source. Since it'd make for an excellent quick reference. Are you porting the site to Angular2? Then I guess I could do it in ionic perhaps.

**Comment by stuartaroth** [comment]
@BasilArackal Sure feel free to do the app or Ionic. The site I initially did in Angular2 however my use of it must have been bad because the Angular2 site ended up being like 6 or 7 mb and took forever to transfer. I did a quick rewrite just using jQuery but I really need to make a lot of improvements to the site in terms of UX and responsiveness.

**Pull request merged**
